-- Executar somente em schema de laboratório. Não executado pelo Maven.
CREATE SEQUENCE PEDIDO_SEQ START WITH 1 INCREMENT BY 1;
CREATE TABLE PEDIDO (ID NUMBER(19) PRIMARY KEY, CLIENTE VARCHAR2(120) NOT NULL, VALOR NUMBER(12,2) NOT NULL);
