<project xmlns="http://maven.apache.org/POM/4.0.0"><modelVersion>4.0.0</modelVersion><parent><groupId>br.com.exemplo.legado</groupId><artifactId>weblogic-pedidos-demo</artifactId><version>1.0.0</version></parent><artifactId>pedidos-ear</artifactId><packaging>ear</packaging>
<dependencies><dependency><groupId>br.com.exemplo.legado</groupId><artifactId>pedidos-web</artifactId><version>${project.version}</version><type>war</type></dependency></dependencies>
<build><finalName>pedidos-legado</finalName><plugins><plugin><groupId>org.apache.maven.plugins</groupId><artifactId>maven-ear-plugin</artifactId><configuration><version>7</version><modules><webModule><groupId>br.com.exemplo.legado</groupId><artifactId>pedidos-web</artifactId><bundleFileName>pedidos.war</bundleFileName><contextRoot>/pedidos</contextRoot></webModule></modules></configuration></plugin></plugins></build></project>
